# Generated by Django 5.2.1 on 2025-05-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_lesson_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enrolled_courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='school.course'),
        ),
    ]
