name: Django CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Remove old migrations and database
        run: |
          cd Learn
          rm -f db.sqlite3
          find . -path "*/migrations/*.py" -not -name "__init__.py" -delete
          find . -path "*/migrations/*.pyc"  -delete
      
      - name: Run migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Run tests
        run: |
          python manage.py test